# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: 5e406c60-md-taco
  namespace: 5e406c60
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: tks
